AWSTemplateVersion: '2010-09-09'
Description: >
  Creating of cloud watch log group for SSH login attempts and Metric filter for tracking failed Counts.
Resources:
  EC2SSHLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: ec2-ssh-logs
      RetentionInDays: 30
      Tags:
      - Key: Environment
        Value: Test
        
  FailedSSHLoginMetricFilter:
  Type: AWS::Logs::MetricFilter
  Properties:
    LogGroupName: !Ref EC2SSHLogGroup
    FilterPattern: "failed"
    MetricTransformations:
      - MetricName: FailedSSHLoginCount
        MetricNamespace: SSH
        MetricValue: "1"
        DefaultValue: 0.0


Outputs:
  LogGroupName:
    Description: AWS CloudWatch Log Group MetricName
    Value: !Ref EC2SSHLogGroup

  MetricDetails:
    Description: Metric is created for tracking SSH failed login attempts
    Value: !sub "Namespace=SSH, MetricName=FailedSSHLoginCount"
